$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: mlflowdp
endpoint_name: mlflow-endpoint-diabetes-mma3
model:
  name: sample-mlflow-sklearn-model
  version: 1
  path: model
  type: mlflow_model
mini_batch_size: 1
compute: azureml:aml-cluster
