channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - mlflow
      - cloudpickle==1.6.0
      - scikit-learn==0.24.2
      - flask==1.1.2
      - applicationinsights
      - pandas
      - azureml-core
      - azureml-dataset-runtime[fuse]
name: mlflow-env
