channels:
  - conda-forge
dependencies:
  - python=3.6.2
  - pip
  - pip:
      - mlflow
      - cloudpickle==1.6.0
      - scikit-learn==0.24.2
      - flask==1.1.2
      - applicationinsights
      - pandas
name: mlflow-env
